trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: test
    displayName: Run tests
    dependsOn: []
    jobs:
    - job: build
      displayName: Build
      steps:

      - task: DotNetCoreCLI@2
        displayName: Run tests
        inputs:
          command: 'test'
          projects: '**/DotnetFriday.Tests/*.csproj'


